### ISSUE TITLE
AWS Lambda failed, succeeded on retry. Look into implementing changes to prevent error from occurring.

### ISSUE THREAD

**Issue by derekwolpert** [rearc-data/who-covid-19-cases-deaths#1]
This was the error message at 12AM ET 5/19/20:

```
[{'Code': 'ACCESS_DENIED_EXCEPTION', 'Message': "Permission Denied. You need permission to write objects to our service's Amazon S3 bucket (s3:PutObject and s3:PutObjectAcl)."}]
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 122, in lambda_handler
    'JobId: 
{}
 failed with errors:\n
{}
'.format(job_id, job_errors))
```

Lambda succeed on retry.

**Comment by derekwolpert** [comment]
When manually testing the lambda at 12:16AM ET 5/19/20:

```
[ERROR] S3UploadFailedError: Failed to upload /tmp/who-covid19-cases-deaths.json to rearc-data-provider/who-covid19-cases-deaths/dataset/who-covid19-cases-deathswho-covid19-cases-deaths.json: An error occurred (SlowDown) when calling the PutObject operation (reached max retries: 4): Please reduce your request rate.
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 73, in lambda_handler
    asset_list = source_dataset(new_filename, s3_bucket, new_s3_key)
  File "/var/task/source_data.py", line 81, in source_dataset
    new_s3_key + filename)
  File "/var/runtime/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/var/runtime/boto3/s3/transfer.py", line 287, in upload_file
    filename, '/'.join([bucket, key]), e))
```

Lambda repeated the error in the first message at 12:18AM.

Successful execution at 12:20AM.

**Comment by derekwolpert** [comment]
This has not be a consistent issue with this product as of late. For the time being this issue is being closed.
